---
- hosts: all
  become: yes
  tasks: 
  - name: i want to copy
    copy:
     src: /etc/passwd
     dest: /tmp
  - name: i want create a folder
    file:
     path: /home/ubuntu/myfile
     state: directory
    tags: myfile

  - name: i want to install apache2
    apt:
     name: apache2
     state: present
    tags: myapache2
  - name: i want to install java 8
    apt:
     name: openjdk-8-jdk 
     state: present
  - name: i want to install tree
    apt: 
     name: tree
     state: present
    tags: mytree 
  - name: i want to install  git 
    apt: 
     name: git
     state: present
    tags: mygit


    
  