---
- hosts: all
  become: yes
  tasks: 
  - name: i want to copy
    copy:
     src: /etc/passwd
     dest: /tmp
  - name: i want create a folder
    file:
     path: /home/ubuntu/myfile
     state: directory
  - name: i want to install apache2
    apt:
     name: apache2
     state: present


    
    